CREATE TABLE IF NOT EXISTS regions (
    region_id BIGINT NOT NULL AUTO_INCREMENT,
    lawd_cd VARCHAR(5) NOT NULL,
    legal_dong_code VARCHAR(10) NULL,
    sido VARCHAR(50) NOT NULL,
    sigungu VARCHAR(50) NOT NULL,
    umd_nm VARCHAR(50) NOT NULL,
    lat DECIMAL(10, 7) NULL,
    lng DECIMAL(10, 7) NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (region_id),
    UNIQUE KEY uq_regions_lawd_umd (lawd_cd, umd_nm),
    KEY idx_regions_lawd_cd (lawd_cd)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS houses (
    house_id BIGINT NOT NULL AUTO_INCREMENT,
    region_id BIGINT NOT NULL,
    sgg_cd VARCHAR(5) NOT NULL,
    umd_nm VARCHAR(50) NOT NULL,
    jibun VARCHAR(30) NOT NULL,
    apt_nm VARCHAR(100) NOT NULL,
    build_year INT NULL,
    lat DECIMAL(10, 7) NULL,
    lng DECIMAL(10, 7) NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (house_id),
    UNIQUE KEY uq_houses_source_identity (sgg_cd, umd_nm, jibun, apt_nm, build_year),
    KEY idx_houses_apt_nm (apt_nm),
    KEY idx_houses_region_id (region_id),
    CONSTRAINT fk_houses_region FOREIGN KEY (region_id) REFERENCES regions (region_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS house_deals (
    deal_id BIGINT NOT NULL AUTO_INCREMENT,
    house_id BIGINT NOT NULL,
    source_api VARCHAR(64) NOT NULL,
    lawd_cd VARCHAR(5) NOT NULL,
    deal_ymd CHAR(6) NOT NULL,
    house_type VARCHAR(30) NOT NULL DEFAULT 'apartment',
    deal_type VARCHAR(30) NOT NULL DEFAULT 'sale',
    deal_year INT NOT NULL,
    deal_month INT NOT NULL,
    deal_day INT NOT NULL,
    deal_date DATE NOT NULL,
    deal_amount VARCHAR(32) NOT NULL,
    deal_amount_manwon INT NULL,
    exclu_use_ar DECIMAL(10, 3) NULL,
    floor INT NULL,
    apt_dong VARCHAR(50) NULL,
    buyer_gbn VARCHAR(50) NULL,
    sler_gbn VARCHAR(50) NULL,
    dealing_gbn VARCHAR(50) NULL,
    estate_agent_sgg_nm VARCHAR(100) NULL,
    cdeal_type VARCHAR(30) NULL,
    cdeal_day VARCHAR(30) NULL,
    rgst_date VARCHAR(30) NULL,
    land_leasehold_gbn VARCHAR(30) NULL,
    api_row_hash CHAR(64) NOT NULL,
    raw_response JSON NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (deal_id),
    UNIQUE KEY uq_house_deals_api_row_hash (api_row_hash),
    KEY idx_house_deals_lawd_ymd (lawd_cd, deal_ymd),
    KEY idx_house_deals_house_date (house_id, deal_date),
    CONSTRAINT fk_house_deals_house FOREIGN KEY (house_id) REFERENCES houses (house_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS public_data_import_batches (
    import_batch_id BIGINT NOT NULL AUTO_INCREMENT,
    source_api VARCHAR(64) NOT NULL,
    lawd_cd VARCHAR(5) NOT NULL,
    deal_ymd CHAR(6) NOT NULL,
    house_type VARCHAR(30) NOT NULL DEFAULT 'apartment',
    deal_type VARCHAR(30) NOT NULL DEFAULT 'sale',
    status VARCHAR(20) NOT NULL,
    total_count INT NOT NULL DEFAULT 0,
    imported_count INT NOT NULL DEFAULT 0,
    skipped_count INT NOT NULL DEFAULT 0,
    error_message TEXT NULL,
    requested_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    completed_at DATETIME NULL,
    PRIMARY KEY (import_batch_id),
    UNIQUE KEY uq_import_batches_request (source_api, lawd_cd, deal_ymd, house_type, deal_type),
    KEY idx_import_batches_lawd_ymd (lawd_cd, deal_ymd)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS members (
    member_id BIGINT NOT NULL AUTO_INCREMENT,
    email VARCHAR(255) NOT NULL,
    password_hash VARCHAR(100) NOT NULL,
    name VARCHAR(100) NOT NULL,
    phone VARCHAR(30) NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (member_id),
    UNIQUE KEY uq_members_email (email)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
